name: release-please

on:
  push:
    branches:
      - main  # Se sua branch principal for 'master', mude aqui

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
